version: "3.8"

services:
  seml_backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seml_backend
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`internals.yao.sh`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  #traefik:
  #    image: traefik:v2.2
  #    ports:
  #        - 8008:80
  #        - 8081:8080
  #    volumes:
  #        - "./traefik.dev.toml:/etc/traefik/traefik.toml"
  #        - "/var/run/docker.sock:/var/run/docker.sock:ro"
