version: '3.8'

services:
    seml_db-master:
        image: yugabytedb/yugabyte:latest
        container_name: seml_db-master-n1
        networks:
            - dbinternal
        volumes:
            - seml-master-data-1:/mnt/master
        command:
            [
                "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=seml_db-master-n1:7100",
                "--rpc_bind_addresses=seml_db-master-n1:7100",
                "--replication_factor=1"
            ]
        ports:
            - "7000:7000"
        environment:
            SERVICE_7000_NAME: yb-master

    seml_db-tserver:
        image: yugabytedb/yugabyte:latest
        container_name: seml_db-tserver-n1
        networks:
            - dbinternal
            - dbnet
        volumes:
            - seml-tserver-data-1:/mnt/tserver
        command:
            [
                "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=seml_db-tserver-n1:9100",
                "--tserver_master_addrs=seml_db-master-n1:7100"
            ]
        ports:
            - "9042:9042"
            - "5433:5433"
            - "9000:9000"
        environment:
            SERVICE_5433_NAME: ysql
            SERVICE_9042_NAME: ycql
            SERVICE_6379_NAME: yedis
            SERVICE_9000_NAME: yb-tserver
        depends_on:
            - seml_db-master
    seml_db-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-py
        networks:
            - dbnet
        ports:
            - "8080:80"
        depends_on:
            - seml_db-tserver
        env_file:
            - .env

volumes:
    seml-master-data-1:
    seml-tserver-data-1:

networks:
    dbinternal:
    dbnet:
